services:
  ubuntu:
    container_name: ubuntu
    build: .
    stdin_open: true
    tty: true
    volumes:
      - .:/home/selenium/project
    working_dir: /home/selenium/project
    links:
      - selenium
      - novnc

  novnc:
    image: javanile/novnc
    environment:
      - REMOTE_HOST=localhost
      - REMOTE_PORT=5900
    ports:
      - "8081:8081"
    links:
      - selenium

  selenium:
    image: selenium/standalone-chrome:latest
    environment:
      - SE_GRID_BROWSER_TIMEOUT=300
      - SE_GRID_SESSION_TIMEOUT=300
      - SCREEN_WIDTH=1280
      - SCREEN_HEIGHT=720
      - SE_NODE_MAX_SESSIONS=2
      - SE_NODE_SESSION_TIMEOUT=300
    ports:
      - "4444:4444"
      - "5900:5900"