name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome-debug:3.11.0-californium
        env:
          VNC_NO_PASSWORD: 1
          SCREEN_WIDTH: 1800
          SCREEN_HEIGHT: 960
        ports:
          - 4444:4444
          - 5900:5900
      novnc:
        image: javanile/novnc
        env:
          REMOTE_HOST: selenium
          REMOTE_PORT: 5900
        ports:
          - 8081:8081

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install docker-compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.23.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Build custom Ubuntu image
        run: docker build -t custom-ubuntu .

      - name: Start Docker Compose services
        run: |
          docker-compose up -d
          # Wait for Selenium to be ready
          until docker run --rm --network host curlimages/curl curl -s http://localhost:4444/wd/hub/status | grep '"ready": true'; do
            echo "Waiting for Selenium to be ready..."
            sleep 2
          done

      - name: Run Gradle tests
        run: |
          docker run --rm \
            --network host \
            -v $(pwd):/home/selenium/project \
            -w /home/selenium/project \
            custom-ubuntu \
            gradle test --no-daemon

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: build/test-results/test/