name: Run Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit-test:
    runs-on: ubuntu-latest

    container:
      image: gradle:8.0.2

    steps:
      - uses: actions/checkout@v3
      - run: gradle test
