name: Run Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  headless-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Set up Chromedriver
        uses: nanasess/setup-chromedriver@v2

      - name: Run Gradle Tests
        env:
          CHROME_BIN: /usr/bin/google-chrome
        run: gradle test
